### ISSUE TITLE
Wont Load new Whatsapp File

### ISSUE THREAD

**Issue by M0nkeynaut** [sinky/whatsapp-chat-export-viewer#1]
Hello. Love the tool and the idea but it does not work with the new Whatsapp Exports.

can you get a hold on that one.

**Comment by M0nkeynaut** [comment]
I found out that the iPhone export has [ infront and in the back of date, time but the android version not.
I think that could be the problem.

**Comment by sinky** [comment]
The Code is made for iOS WhatsApp only right now. Inhave no time to work on Android compatibility.
